// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Campaigns        string
	Locations        string
	PlayerCharacters string
	SubLocations     string
	Users            string
}{
	Campaigns:        "campaigns",
	Locations:        "locations",
	PlayerCharacters: "player_characters",
	SubLocations:     "sub_locations",
	Users:            "users",
}
